"""empty message

Revision ID: 523babb1066f
Revises: 6cbf76703309
Create Date: 2022-04-15 23:00:58.905802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523babb1066f'
down_revision = '6cbf76703309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_de_nascimento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tabela_exemplo')
    op.alter_column('Alugueis', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('Alugueis', 'imovel',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Alugueis', 'proprietario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Contratos', sa.Column('aluguel', sa.Integer(), nullable=True))
    op.add_column('Contratos', sa.Column('inquilino', sa.Integer(), nullable=True))
    op.drop_constraint('inquilino do aluguel_id_aluguel_foreign', 'Contratos', type_='foreignkey')
    op.drop_constraint('inquilino do aluguel_id_inquilino_foreign', 'Contratos', type_='foreignkey')
    op.create_foreign_key(None, 'Contratos', 'Inquilinos', ['inquilino'], ['id'])
    op.create_foreign_key(None, 'Contratos', 'Alugueis', ['aluguel'], ['id'])
    op.drop_column('Contratos', 'id_inquilino')
    op.drop_column('Contratos', 'id_aluguel')
    op.alter_column('Imoveis', 'logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Imoveis', 'cep',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Imoveis', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Imoveis', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Inquilinos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Inquilinos', 'data_de_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Proprietarios', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Proprietarios', 'data_de_nascimento',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Proprietarios', 'data_de_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Proprietarios', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Inquilinos', 'data_de_nascimento',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Inquilinos', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Imoveis', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Imoveis', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Imoveis', 'cep',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Imoveis', 'logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('Contratos', sa.Column('id_aluguel', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Contratos', sa.Column('id_inquilino', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Contratos', type_='foreignkey')
    op.drop_constraint(None, 'Contratos', type_='foreignkey')
    op.create_foreign_key('inquilino do aluguel_id_inquilino_foreign', 'Contratos', 'Inquilinos', ['id_inquilino'], ['id'])
    op.create_foreign_key('inquilino do aluguel_id_aluguel_foreign', 'Contratos', 'Alugueis', ['id_aluguel'], ['id'])
    op.drop_column('Contratos', 'inquilino')
    op.drop_column('Contratos', 'aluguel')
    op.alter_column('Alugueis', 'proprietario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Alugueis', 'imovel',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Alugueis', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('tabela_exemplo',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.drop_table('individuo')
    # ### end Alembic commands ###
