"""empty message

Revision ID: 6cbf76703309
Revises: 
Create Date: 2022-04-15 21:15:24.273991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbf76703309'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individuo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_de_nascimento', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Proprietarios')
    op.drop_table('Inquilino do aluguel')
    op.drop_table('Alugueis')
    op.drop_table('tabela_exemplo')
    op.drop_table('Inquilinos')
    op.alter_column('Imoveis', 'logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Imoveis', 'cep',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Imoveis', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('Imoveis', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Imoveis', 'cidade',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Imoveis', 'bairro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('Imoveis', 'cep',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Imoveis', 'logradouro',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('Inquilinos',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_de_nascimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Inquilinos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('tabela_exemplo',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    op.create_table('Alugueis',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('imovel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proprietario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['imovel'], ['Imoveis.id'], name='alugueis_imovel_foreign'),
    sa.ForeignKeyConstraint(['proprietario'], ['Proprietarios.id'], name='alugueis_proprietario_foreign'),
    sa.PrimaryKeyConstraint('id', name='Alugueis_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Inquilino do aluguel',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_inquilino', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_aluguel', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_aluguel'], ['Alugueis.id'], name='inquilino do aluguel_id_aluguel_foreign'),
    sa.ForeignKeyConstraint(['id_inquilino'], ['Inquilinos.id'], name='inquilino do aluguel_id_inquilino_foreign'),
    sa.PrimaryKeyConstraint('id', name='Inquilino do aluguel_pkey')
    )
    op.create_table('Proprietarios',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('data_de_nascimento', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Proprietarios_pkey')
    )
    op.drop_table('individuo')
    # ### end Alembic commands ###
